name: vibevoice-standalone
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - torchaudio>=2.0.0
  - pip
  - pip:
    - accelerate>=1.6.0
    - transformers>=4.51.3
    - diffusers
    - gradio>=4.0.0
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - tqdm
    - scipy
    - ml-collections
    - numpy>=1.20.0
    - librosa>=0.9.0
    - soundfile>=0.12.0
    - av>=14.3.0
    - peft>=0.17.0
    - huggingface_hub>=0.25.1
    - absl-py
    - bitsandbytes>=0.48.1
    - protobuf
    - python-multipart
    - aiofiles
    - flash-attn>=2.0.0
